# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specledger < Formula
  desc "Unified CLI for project bootstrap and specification dependency management"
  homepage "https://github.com/specledger/specledger"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/specledger/specledger/releases/download/v1.1.0/specledger_1.1.0_darwin_amd64.tar.gz"
      sha256 "c9ce997666e31b3e419366e5f3bd691a64998dc31d11ae4b49b76f3862fffaee"

      define_method(:install) do
        bin.install "sl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/specledger/specledger/releases/download/v1.1.0/specledger_1.1.0_darwin_arm64.tar.gz"
      sha256 "2bdfa1171d3394aadb6917e7b1cb77f43f5e71a2d10cc636f9aaa49a82fccf27"

      define_method(:install) do
        bin.install "sl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/specledger/specledger/releases/download/v1.1.0/specledger_1.1.0_linux_amd64.tar.gz"
      sha256 "eab7cb611da1a579de6a0ead7722edc695802ed75bceee16bbc0fb1b9520ebf0"
      define_method(:install) do
        bin.install "sl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/specledger/specledger/releases/download/v1.1.0/specledger_1.1.0_linux_arm64.tar.gz"
      sha256 "037a31e124e3226af0f815100009003dafc55c50e5bdc7dbbf2dab60ed362516"
      define_method(:install) do
        bin.install "sl"
      end
    end
  end
end
