# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specledger < Formula
  desc "Unified CLI for project bootstrap and specification dependency management"
  homepage "https://github.com/specledger/specledger"
  version "1.0.35"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/specledger/specledger/releases/download/v1.0.35/specledger_1.0.35_darwin_amd64.tar.gz"
      sha256 "184e8e341c4fddbb76315eea684a6417e32f5347df03f349ce85987b0aa73b80"

      define_method(:install) do
        bin.install "sl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/specledger/specledger/releases/download/v1.0.35/specledger_1.0.35_darwin_arm64.tar.gz"
      sha256 "4966afe1f9d332c8384df0a0851bd088de86ec252ff01f6f39c4c810afc9fa52"

      define_method(:install) do
        bin.install "sl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/specledger/specledger/releases/download/v1.0.35/specledger_1.0.35_linux_amd64.tar.gz"
      sha256 "0f3ab20c9979d21a5fe85ee24da449c9fb0219df782a8699325844c971854631"
      define_method(:install) do
        bin.install "sl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/specledger/specledger/releases/download/v1.0.35/specledger_1.0.35_linux_arm64.tar.gz"
      sha256 "d77048a9d4ac060d075a0efe3e98bb2fd5ab0619270a5f7ed100ec12009d53a7"
      define_method(:install) do
        bin.install "sl"
      end
    end
  end
end
